[package]
name = "2i-emulator"
version = "0.3.0"
authors = ["Klemens Schölhorn <klemens@schoelhorn.eu>"]

[lib]
name = "emulator"
path = "src/emulator/lib.rs"

[[bin]]
name = "2i-emulator"
path = "src/cli/main.rs"

[dependencies]
linenoise-rust = "0.2.0"
regex = "0.1"
